# Generated by Django 4.1 on 2022-09-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHealthapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
