# Generated by Django 4.1 on 2022-09-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHealthapp', '0002_posts_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
    ]
