# Generated by Django 4.1 on 2022-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHealthapp', '0004_alter_posts_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='audio_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='music'),
        ),
    ]
